name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  node-test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules and build
        run: |
          yarn
          yarn bootstrap
          yarn build
      - name: Run tests
        run: yarn test:node

  deno-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        deno: ["v1.2.0", "v1.5.0", "v1.x", "nightly"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Install modules and build
        run: |
          yarn
          yarn bootstrap
          yarn build
      - name: Run Deno tests
        run: yarn test:deno
